### ISSUE TITLE
Not working with IIS

### ISSUE THREAD

**Issue by denniskalpedis** [Sicos1977/ChromeHtmlToPdf#21]
I saw the other issue with getting it to work with IIS, I'm having the same issue. it could not start chrome, retried 5 times.

I grabbed chrome portable from https://www.chrome-portable.com/ and put it in the same DIR but it gives the same error.

I have tried to call the exe from command line
```c#
            System.Diagnostics.Process process = new System.Diagnostics.Process();
            System.Diagnostics.ProcessStartInfo startInfo = new 
            System.Diagnostics.ProcessStartInfo();
            startInfo.RedirectStandardOutput = true;
            startInfo.RedirectStandardError = true;
            startInfo.UseShellExecute = false;
            startInfo.CreateNoWindow = true;
            startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
            startInfo.FileName = "cmd.exe";
            startInfo.Arguments = "/C ";
            startInfo.Arguments += System.Web.HttpContext.Current.Server.MapPath("/ChromeHtmlToPdf/ChromeHtmlToPdf.exe");
            startInfo.Arguments += " --print-background --input \"";
            startInfo.Arguments += Url;
            startInfo.Arguments += "\" --output ";
            startInfo.Arguments += System.Web.HttpContext.Current.Server.MapPath("/Reports/export.pdf");

            process.StartInfo = startInfo;
            process.Start();
            
            process.WaitForExit();
```

It gives me this.

```
2019-04-25T16:29:27.624 -    at ChromeHtmlToPdfLib.Converter.StartChromeHeadless()
   at ChromeHtmlToPdfLib.Converter.ConvertToPdf(ConvertUri inputUri, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, Stream logStream)
   at ChromeHtmlToPdfLib.Converter.ConvertToPdf(ConvertUri inputUri, String outputFile, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, Stream logStream)
   at ChromeHtmlToPdf.Program.Convert(Options options)
   at ChromeHtmlToPdf.Program.Main(String[] args), Chrome exited unexpectedly, One or more arguments are invalid (Exception from HRESULT: 0x80000003)
```

also tried 

```c#
            using (var converter = new Converter(System.Web.HttpContext.Current.Server.MapPath("/chrome64/GoogleChromePortable.exe")))
            {
                var sets = new PageSettings(ChromeHtmlToPdfLib.Enums.PaperFormat.A4);
                sets.PrintBackground = true;
                converter.ConvertToPdf(new Uri(Url), System.Web.HttpContext.Current.Server.MapPath("/Reports/test.pdf"), sets, false);
            }
```

same error.

**Comment by Sicos1977** [comment]
Under what user are you calling chrome? If you use local system then it won't work. Try to use a local user that you have added to the user or admin group
